name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: yarn install
      - name: build
        run: yarn workspaces run build
      - name: lint
        run: yarn workspaces run lint
      - name: test
        run: yarn workspaces run test || (cat playground.log && false)
